spring:
  application:
    name: springcache
  profiles:
    active: test
# 底层使用ehcache缓存
#  cache:
#    type: ehcache
#    ehcache:
#      config: classpath:/ehcache.xml
server:
  port: 9097
  servlet:
    context-path: /springcache
study:
  service:
    version: 1.0.0
dubbo:
  scan:
    basePackages: com.fullmoon.study
  application:
    id: springcache-provider-local
    name: springcache-provider-local
    qos-port: 0
  protocol:
    id: dubbo
    name: dubbo
    port: 8070
    status: server
  registry:
    id: remote-registry
    address: zookeeper://192.250.110.153:2181
    protocol: zookeeper