spring:
  application:
    name: jetcache
  profiles:
    active: test
server:
  port: 9091
  servlet:
    context-path: /jetcache
study:
  service:
    version: 1.0.0
dubbo:
  scan:
    basePackages: com.fullmoon.study
  application:
    id: jetcache-provider
    name: jetcache-provider
    qos-port: 0
  protocol:
    id: dubbo
    name: dubbo
    port: 9093
    status: server
  registry:
    id: remote-registry
    address: zookeeper://192.250.110.153:2181
    protocol: zookeeper
#jetCache相关公共配置
jetcache:
  statIntervalMinutes: 5 #统计时间间隔
  areaInCacheName: false #设置不把areaName作为key的前缀
  hiddenPackages: com.fullmoon.study #如果@Cached或者@CreateCached的自动生成的，会默认将包名和方法名作为前缀，为了不让name太长将该包名去掉
  local:
    default:
      type: caffeine #本地缓存类型caffeine、linkedhashmap
      limit: 100 #每个缓存示例的最大元素的全局变量
      keyConvertor: fastjson #key的转换器fastjson
      expireAfterWriteInMillis: 600000 #默认全局超时时间为10分钟
      expireAfterAccessInMillis: 300000 #本地缓存默认5分钟没有访问则失效
  remote:
    default:
      type: redis.lettuce #lettuce为redis的java客户端，支持异步
      keyConvertor: fastjson #key的转换器fastjson
      valueEncoder: java #序列化器的全局配置，仅remote类型的缓存需要指定，可选java和kryo
      valueDecoder: java #序列化器的全局配置，仅remote类型的缓存需要指定，可选java和kryo
      expireAfterWriteInMillis: 3600000 #默认全局超时时间为1小时
      poolConfig:
        minIdle: 10
        maxIdle: 20
        maxTotal: 50
      uri: redis-sentinel://192.250.110.171:26379,192.250.110.170:26379,192.250.110.172:26379/?sentinelMasterId=mymaster