spring:
  application:
    name: jetcache
  profiles:
    active: test
server:
  port: 9094
  servlet:
    context-path: /jetcache
study:
  service:
    version: 1.0.0
dubbo:
  scan:
    basePackages: com.fullmoon.study
  application:
    id: jetcache-consumer
    name: jetcache-consumer
  registry:
    id: remote-registry
    address: zookeeper://192.250.110.153:2181
    protocol: zookeeper