jasypt:
  encryptor:
    password: f77b2bcf9db04848ba9742254c25d996 # salt 盐值，需要和加密时使用的 salt 一致
    algorithm: PBEWithMD5AndDES # 加密算法，需要和加密时使用的算法一致
    string-output-type: hexadecimal # 密文格式，需要和加密时使用的输出格式一致
server:
  port: 9092
  servlet:
    context-path: /basic
  tomcat:
    accept-count: 200
    min-spare-threads: 200
spring:
  application:
    name: basic
  profiles:
    active: test
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver # 不配置则会根据 url 自动识别
      initial-size: 5 # 初始化时建立物理连接的个数
      min-idle: 20 # 最小连接池数量
      max-active: 20 # 最大连接池数量
      max-wait: 10000 # 获取连接时最大等待时间，单位毫秒
      validation-query: SELECT 1 # 用来检测连接是否有效的 sql
      test-while-idle: true # 申请连接的时候检测，如果空闲时间大于 timeBetweenEvictionRunsMillis，则执行 validationQuery 检测连接是否有效
      test-on-borrow: false # 申请连接时执行 validationQuery 检测连接是否有效
      min-evictable-idle-time-millis: 120000 # 连接保持空闲而不被驱逐的最小时间，单位是毫秒
      time-between-eviction-runs-millis: 3600000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      filters: stat,log4j,wall # 配置过滤器，stat-监控统计，log4j-日志，wall-防御 SQL 注入
      connection-properties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000' # StatFilter配置，打开合并 SQL 功能和慢 SQL 记录
      web-stat-filter: # WebStatFilter 配置
        enabled: true
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet: # StatViewServlet 配置
        enabled: true
        url-pattern: '/druid/*'
        reset-enable: false
        login-username: druid
        login-password: druid
      aop-patterns: 'com.fullmoon.study.service.*' # Spring 监控配置
mybatis:
  type-aliases-package: com.fullmoon.study.entity
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true # 分页合理化参数
  offset-as-page-num: true # 将 RowBounds 中的 offset 参数当成 pageNum 使用
  supportMethodsArguments: true # 支持通过 Mapper 接口参数来传递分页参数

# 测试环境
---
spring:
  profiles: test
  datasource:
    druid:
      url: jdbc:mysql://192.250.110.158:3306/gsfy_user?useUnicode=true&characterEncoding=utf8
      username: root
      password: ENC(70EA8EBF557526106C1C9030CF217D2EF9405A25021FEB999575EEAD1841E70B) # Jasypt 密文格式：ENC(密文)
