spring:
  application:
    name: basic
  profiles:
    active: test
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5 #初始化时建立物理连接的个数,初始化发生在显示调用init方法或第一次getConnection时
    minIdle: 20 #最小连接池数量
    maxActive: 20 #最大连接池数量
    maxWait: 10000 #获取连接时最大等待时间(ms)配置了maxWait之后,缺省启用公平锁,并发效率会有所下降,如果需要可以通过配置useUnfairLock属性为true使用非公平锁
    filters: stat,log4j,wall #过滤器配置
    timeBetweenEvictionRunsMillis: 3600000 #在指定时间间隔(ms)内执行一次空闲连接回收器
    minEvictableIdleTimeMillis: 120000 #池中的连接空闲指定时间(ms)后被回收
    testWhileIdle: true #指明连接是否被空闲连接回收器(如果有)进行检验
    testOnBorrow: false #否在从池中取出连接前进行检验
    testOnReturn: false #是否在归还到池中前进行检验
server:
  port: 9092
  servlet:
    context-path: /basic
  tomcat:
    accept-count: 200
    min-spare-threads: 200
mybatis:
  type-aliases-package: com.fullmoon.study.entity
  mapper-locations: classpath:*Mapper.xml

#测试环境
---
spring:
  profiles: test
  datasource:
    username: dev
    password: 1qaz@WSX
    url: jdbc:mysql://192.250.110.158:3306/gsfy_user?useUnicode=true&amp;characterEncoding=utf8